Building DAG of jobs...
Provided cores: 4
Rules claiming more threads will be scaled down.
Job stats:
job              count
-------------  -------
all                  1
dynamic_solve      216
solve_base           2
total              219

Select jobs to execute...

[Sun Jun 16 22:42:04 2024]
rule solve_base:
    input: resources/DE_20_1.0_base.nc
    output: resources/DE_20_1.0_base_solved.nc, resources/DE_20_1.0_base_roll_solved.nc
    jobid: 2
    reason: Missing output files: resources/DE_20_1.0_base_solved.nc
    wildcards: country=DE, buses=20, transmission_limit=1.0
    resources: tmpdir=C:\Users\Jeremy\AppData\Local\Temp


[Sun Jun 16 22:42:04 2024]
rule solve_base:
    input: resources/DE_20_1.5_base.nc
    output: resources/DE_20_1.5_base_solved.nc, resources/DE_20_1.5_base_roll_solved.nc
    jobid: 111
    reason: Missing output files: resources/DE_20_1.5_base_solved.nc
    wildcards: country=DE, buses=20, transmission_limit=1.5
    resources: tmpdir=C:\Users\Jeremy\AppData\Local\Temp

[Sun Jun 16 22:42:30 2024]
Error in rule solve_base:
    jobid: 2
    input: resources/DE_20_1.0_base.nc
    output: resources/DE_20_1.0_base_solved.nc, resources/DE_20_1.0_base_roll_solved.nc

[Sun Jun 16 22:42:30 2024]
Error in rule solve_base:
    jobid: 111
    input: resources/DE_20_1.5_base.nc
    output: resources/DE_20_1.5_base_solved.nc, resources/DE_20_1.5_base_roll_solved.nc

RuleException:
CalledProcessError in file C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile, line 138:
Command 'python scripts/solve_base.py resources/DE_20_1.0_base.nc resources/DE_20_1.0_base_solved.nc 130 resources/DE_20_1.0_base_roll_solved.nc 52 EQ0.95c DE 1.0 20' returned non-zero exit status 3221225786.
  File "C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile", line 138, in __rule_solve_base
  File "C:\Users\Jeremy\anaconda3\envs\pypsa-eur\Lib\concurrent\futures\thread.py", line 58, in run
RuleException:
CalledProcessError in file C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile, line 138:
Command 'python scripts/solve_base.py resources/DE_20_1.5_base.nc resources/DE_20_1.5_base_solved.nc 130 resources/DE_20_1.5_base_roll_solved.nc 52 EQ0.95c DE 1.5 20' returned non-zero exit status 3221225786.
  File "C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile", line 138, in __rule_solve_base
  File "C:\Users\Jeremy\anaconda3\envs\pypsa-eur\Lib\concurrent\futures\thread.py", line 58, in run
Terminating processes on user request, this might take some time.
Complete log: .snakemake\log\2024-06-16T224159.872219.snakemake.log
