Building DAG of jobs...
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job              count
-------------  -------
all                  1
dynamic_solve       72
total               73

Select jobs to execute...

[Fri May 31 23:00:50 2024]
rule dynamic_solve:
    input: resources/DE_20_1.0_base_solved.nc
    output: resources/DE_20_1.0_pv_0.25_90_inv.nc, results/DE_20_1.0_pv_0.25_90_invroll.nc
    jobid: 5
    reason: Code has changed since last execution
    wildcards: country=DE, buses=20, transmission_limit=1.0, contingency=pv, reductionto=0.25, duration=90, model=inv
    resources: tmpdir=C:\Users\Jeremy\AppData\Local\Temp

[Fri May 31 23:01:10 2024]
Error in rule dynamic_solve:
    jobid: 5
    input: resources/DE_20_1.0_base_solved.nc
    output: resources/DE_20_1.0_pv_0.25_90_inv.nc, results/DE_20_1.0_pv_0.25_90_invroll.nc

RuleException:
CalledProcessError in file C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile, line 150:
Command 'python scripts/solve_pv.py resources/DE_20_1.0_base_solved.nc resources/DE_20_1.0_pv_0.25_90_inv.nc results/DE_20_1.0_pv_0.25_90_invroll.nc pv 0.25 90 inv 24 2013-02-01 00:00:00' returned non-zero exit status 3221225786.
  File "C:\Users\Jeremy\Documents\MasterThesis\Models\Snakefile", line 150, in __rule_dynamic_solve
  File "C:\Users\Jeremy\anaconda3\envs\pypsa-eur\Lib\concurrent\futures\thread.py", line 58, in run
Terminating processes on user request, this might take some time.
Complete log: .snakemake\log\2024-05-31T230048.062071.snakemake.log
